spring:
  datasource:
    url: jdbc:sqlite:./data/qyuan.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:

  cloud:
    nacos:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false

  # 开发工具配置
  devtools:
    restart:
      enabled: true  # 启用自动重启
      additional-paths: src/main/java  # 监听额外路径
      exclude: static/**,public/**  # 排除不需要热重载的目录
    livereload:
      enabled: true  # 启用 live reload
    # 远程开发支持
    remote:
      secret: mysecret  # 远程连接密钥

huawei:
  obs:
    enabled: true
    endpoint: ${HUAWEICLOUD_SDK_ENDPOINT}
    accessKey: ${HUAWEICLOUD_SDK_AK}
    secretAccessKey: ${HUAWEICLOUD_SDK_SK}
    bucketName: ${HUAWEICLOUD_SDK_BUCKET_NAME}
    expiration: 60

minio:
  endpoint: http://120.46.205.113:9098
  accessKey: admin
  secretKey: QianYuanWanMa_18
  bucketName: audit

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  packages-to-scan: com.example.qyuanpaperrd.controller
  paths-to-match: /paper/**

logging:
  level:
    com.example.qyuanpaperrd: DEBUG