apiVersion: apps/v1
kind: Deployment
metadata:
  name: qyuan-social
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qyuan-social
  template:
    metadata:
      labels:
        app: qyuan-social
    spec:
      containers:
        - name: qyuan-social
          image: 192.168.0.7:5000/qyuan-social:latest
          ports:
            - containerPort: 9003
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
            - name: TZ
              value: "Asia/Shanghai"
            - name: LANG
              value: C.UTF-8
---
apiVersion: v1
kind: Service
metadata:
  name: qyuan-social-service
  namespace: default
spec:
  selector:
    app: qyuan-social
  ports:
    - port: 9003
      targetPort: 9003
      protocol: TCP
  type: ClusterIP

